version: "3"

services:
    api:
        env_file: .env
        container_name: 'alvo-container'
        image: alvo-api
        command: bash -c "./scripts/wait_for_it.sh --timeout=0 ${DB_HOST}:${DB_PORT} && npm run start"
        ports:
            - 80:${PORT}
        restart: unless-stopped